### ISSUE TITLE
Repellent gathering is identical for all animals

### ISSUE THREAD

**Issue by SorraTheOrc** [TheWizardsCode/Versus#13]
Since all animals gather repellent at the same rate they all start laying mines at the same time. We need to vary it a little. The fist ting to do would be to:

- [X] randomize the amount gathered each tick.

A more interesting thing would be to:

- [x] increase the rate of repellent gathering based on level

**Comment by bsimser** [comment]
This is complete now right? The randomization based on level? You did that in the OnLevelChanged call in AnimalController.

**Comment by SorraTheOrc** [comment]
Well you did it, yes. I just moved it ;-)
