### ISSUE TITLE
Dogs and Cats shouldn't go into buildings

### ISSUE THREAD

**Issue by SorraTheOrc** [TheWizardsCode/Versus#36]
The current movement system allows dogs and cats to walk through buildings. This makes it really hard for the player in FPS to create any kind of tactic for protecting themselves. 

The easiest way to change this will be to use NavMesh movement. I'm not sure of the perf impact of this so we may need to do something smart with a LOD based movement system. Lets do some profiling first.

**Comment by bsimser** [comment]
I assumed there were colliders on the buildings and animals. Why can't we use those?

**Comment by SorraTheOrc** [comment]
We could but that requires us to build a navigation system that will avoid the buildings. That's easy for when they are just wandering around in the block but when they are fleeing they will need to find a path between buildings. Similarly when they are attacking the player they will need to navigate around buildings, obstacles and each other. Finally, we want the cats to hold the high ground, so we will have to add in a form of 3D navigation.

With NavMesh we get all that for free. So I think it would be best to try NavMesh perf first.
________________________________

**Comment by bsimser** [comment]
Agreed we need to use NavMesh (I don't think there's a perf hit, it's the standard thing you use for this). We still need colliders on the animals and buildings, otherwise the player will run through them. I think a NavMesh with some coding will fix the issue at hand so the animals won't go wandering through multiple dimensions.

**Comment by SorraTheOrc** [comment]
Currently there are no colliders. Colliders are expensive it's best to avoid them if you can. If we generate a navmesh we can use that to prevent the player from walking into buildings as well. Whether that is the right approach or not is the topic of a different (yet to be created issue) though. The core question will be do the colliders add additional value (I think they probably will - such as being able to bounce repellent grenades around corners, doing parkour etc.)

________________________________

**Comment by SorraTheOrc** [comment]
I'm going to close this out. Having playtested I kind of like that the animals can go into the buildings. Lets see if it sticks
