### ISSUE TITLE
Switching to top down mode from FPS mode isn't working anymore

### ISSUE THREAD

**Issue by bsimser** [TheWizardsCode/Versus#66]
This was working a few days ago but was broken yesterday (i.e. my latest PR didn't cause it). 

Steps to reproduce:
1. Run game
2. Select a city block and go into FPS mode (left click)
3. Press escape
4. Select Top Down Mode

Expected behavior:
* Should return to Top Down Mode

Actual behavior:
* Does nothing

**Comment by SorraTheOrc** [comment]
This is likely a result of your recent UI work. As it was working last night. There is a connection between the scripts and the UI components. You mentioned you did your work in a copy then ported the components into the main thread. So some references have likely been lost. If there is no error message then it is probably being swallowed somewhere. Look for missing references in the UI components for the FPS HUD.

I'll merge your PR soon and will take a look at it if you don't get to it first.

**Comment by bsimser** [comment]
No this bug was there before I started the UI changes as I was experiencing it yesterday before I started work on that. There were broken references in the main scene when I made the new UI prefabs but those were fixed in the PR and should work fine. I think the top down switch is something else but will look into it once we get the code merged.

**Comment by SorraTheOrc** [comment]
Just realized I have it open in front of me, no time to fix now, but can do later.

![image](https://user-images.githubusercontent.com/250240/145320208-c77df831-30f9-4fd9-91ac-85c4e0334ccb.png)

in

![image](https://user-images.githubusercontent.com/250240/145320286-61597ad3-c241-49c3-a659-bdfac02b6a0b.png)

**Comment by bsimser** [comment]
Simple fix. Good find.
